### ISSUE TITLE
u4 remove quote

### ISSUE THREAD

**Issue by chloecwh** [twu-innovation/inno101#15]
https://github.com/twu-innovation/inno101/blob/b98ebc4daaffc7e97e65ce5963650695d716db8c/u4.qmd#L91

```
**So What is a Personal Learning Environment?**

Personal Learning Environments [are] systems that help learners take control of and manage their own learning. This includes providing support for learners to set their own learning goals, manage their learning; managing both content and process, communicate with others in the process of learning, and thereby achieve learning goals. A PLE may be composed of one or more sub-systems: As such it may be a desktop application, or composed of one or more web-based services. (van Harmelen, 2007, as cited in Edutech Wiki, 2014, Definitions, para. 2) 

<!-- As described by Casteneda et al.,

A Personal Learning Environment is … a structure and process that helps learners organize the influx of information, resources and interactions that they are faced with on a daily basis into a personalized learning space or experience. In a PLE, the learner develops an individualized digital identity through the perceptual cues and cognitive affordances that the personal learning environment provides, such as what information to share and when, who to share it with, and how to effectively merge formal and informal learning experiences. (2017, para. 2) -->

Which aspects of the two definitions do you find most meaningful? How do you structure your daily interactions and manage the flow of information? In what ways do you communicate your learning experiences to others? Lastly, what specific goals are you aiming to accomplish through your learning journey?

```

https://github.com/twu-innovation/inno101/issues/13#issue-2469507411

This is @kmarjanovic request: 

remove 2nd quote in 4.1 Personal Learning Environments
 A Personal Learning Environment is “a structure and process that helps learners organize the influx of information, resources and interactions that they are faced with on a daily basis into a personalized learning space or experience. In a PLE, the learner develops an individualized digital identity through the perceptual cues and cognitive affordances that the personal learning environment provides, such as what information to share and when, who to share it with, and how to effectively merge formal and informal learning experiences (Castañeda, Cosgrave, Marín, Cronin, 2016) cited in Personal Learning Environments: Research-Based Practices, Frameworks and Challenges.

Removing the 2nd quote would affect the question, how do you suggest to edit this text? Thanks !

**Comment by kmarjanovic** [comment]
@chloecwh good catch!  Please keep both quotes.  Thanks!

**Comment by chloecwh** [comment]
![Screenshot 2024-11-12 at 9 07 18 AM](https://github.com/user-attachments/assets/750b7f2e-53b0-4bae-a246-74c87c922fa6)

added block quote to both quotes
