### ISSUE TITLE
Activity 5.1.4

### ISSUE THREAD

**Issue by chloecwh** [twu-innovation/inno101#18]
```
@kmarjanovic's comment

deleting 'Bill of Rights' Seeks to Protect Students' Interests as Online Learning Rapidly Expands (2013) & Critique of 'Bill of Rights and Principles for Learning in the Digital Age (2013)
@chloe how does this work with Zotero?  Should I delete from the library? 

On another issue - I want to add this video to the beginning of this activity, but the formatting isn't quite working.  please embed https://www.youtube.com/watch?v=QpNeavL0Dfw

- Watch the Your Digital Rights and Responsibilities| Being a Good Digital Citizen

```

- deleting 'Bill of Rights' Seeks to Protect Students' Interests as Online Learning Rapidly Expands (2013) - done
- Critique of 'Bill of Rights and Principles for Learning in the Digital Age (2013) - cannot find it 
- unused resources on Zotero, not sure if who's deleting it
- added new video 

In file u5.qmd
https://github.com/twu-innovation/inno101/blob/f87930097fee100076144388249f6e777bfab923/u5.qmd#L167

**Comment by kmarjanovic** [comment]
looks good to me!  I'll delete unused Zotero resources.
