### ISSUE TITLE
5.4.1 missing hyperlinks

### ISSUE THREAD

**Issue by chloecwh** [twu-innovation/inno101#23]
missing hyperlinks to TWU social media channels

```
**TWU on Social Media**

Here are some other websites you might want to check out for more about the TWU community:

- TWU Facebook
- X (Twitter)
- Instagram
```

In file u5.qmd
https://github.com/TWUOnline/inno101-q/blob/b47417c329746ea9b55e6b57da26929323f7f45a/u5.qmd#L485

**Comment by kmarjanovic** [comment]
https://www.facebook.com/trinitywestern
https://x.com/TrinityWestern
https://www.instagram.com/trinitywestern/?hl=en
