### ISSUE TITLE
2.2.2

### ISSUE THREAD

**Issue by chloecwh** [twu-innovation/inno101#24]
From Kelly  

https://github.com/twu-innovation/inno101/commit/f87930097fee100076144388249f6e777bfab923#diff-9b5921b76c9ae5041e282eed6fdd61d4e288986adc201ea3e023c14e126b9bf3

```

### Activity: Wikipedia: Why or Why Not?

::: learning-activity
Consider the following statement: Wikipedia is a reliable source for academic study.

Do you agree? Have you cited Wikipedia in any academic work? Why or why not?

- Read the following:
    - [Is Wikipedia a Trustworthy Academic Resource? Scientists Think So](https://edtechmagazine.com/higher/article/2017/12/wikipedia-trustworthy-academic-resource-scientists-think-so){target="_blank"} published by EdTech Magazine.
    - [Reliability of Wikipedia](https://en.wikipedia.org/wiki/Reliability_of_Wikipedia){target="_blank"} article on Wikipedia.
    - [*Should University Students use Wikipedia?*](https://www.theguardian.com/education/2013/may/13/should-university-students-use-wikipedia){target="_blank"} (2013)
    - Optional reading annotations: Conduct a search for credible and reliable resources on the topic of the reliability and credibility of Wikipedia articles.
- [*Watch:* *Using Wikipedia for Academic Research*](https://www.youtube-nocookie.com/embed/Cql_yVUYj6A){target="_blank"} (2011)

{{< video https://www.youtube-nocookie.com/embed/Cql_yVUYj6A >}}

Drawing on your study of the reliability and credibility of online resources, share your advice to fellow learners in this course regarding the use of Wikipedia for academic purposes by posting a comment on Discourse. For example:

- You can use Wikipedia for ... because ...
- You should not use Wikipedia for ... because ...

```

In file u2.qmd
https://github.com/TWUOnline/inno101-q/blob/b47417c329746ea9b55e6b57da26929323f7f45a/u2.qmd#L467

**Comment by kmarjanovic** [comment]
@chloecwh could you let me know what you need from me in these issues?  
I'm previewing section 2.2.2 in VS code and it looks fine.

**Comment by chloecwh** [comment]
@kmarjanovic the message did not sent over to GH successfully, my goal was to create a todo ticket with tags incase Colin missed it

From Kelly to Colin, "@cmadland please add to section 
e.g. https://pressbooks.pub/webliteracy/
 **Web Literacy for Student Fact-Checkers**"

**Comment by kmarjanovic** [comment]
okay - I've added the note to Colin to our [QA doc](https://mytwu.sharepoint.com/:w:/r/sites/LearningDesign/Shared%20Documents/Course%20Quality%20Reviews/LDRS%20101_TWU%20Online%20Course%20Quality%20Review%20-%20TOP.docx?d=wb70d1e68e61f418d8ea091df1840c674&csf=1&web=1&e=3244gJ), so will close the issue here
